---

- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Login to registry
  containers.podman.podman_login:
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    registry: "{{ registry_url }}"

- name: Pull jupyter-server image
  containers.podman.podman_image:
    name: "{{ registry_url }}/makers-ns/gozinc2023/notebook:latest"
    pull: true

- name: Create env files directory
  ansible.builtin.file:
    path: /etc/gozinc/config.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create env files
  ansible.builtin.template:
    src: config.env.j2
    dest: "/etc/gozinc/config.d/{{ item.name }}.env"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ users }}"

- name: Create jupyter-server service
  ansible.builtin.template:
    src: jupyter-server@.service.j2
    dest: /etc/systemd/system/jupyter-server@.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart jupyter-server

- name: Enable jupyter-server
  ansible.builtin.systemd:
    name: "jupyter-server@{{ item.name }}"
    enabled: true
    daemon_reload: true
  loop: "{{ users }}"
