---

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Allow nginx to be a proxy
  ansible.posix.seboolean:
    name: httpd_can_network_relay
    state: true
    persistent: true

- name: Allow nginx to connect to the internet
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Allow nginx to connect to ports
  community.general.seport:
    ports: "{{ item.port }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop: "{{ users }}"

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Create nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx
